toy = ["republican", 'economy', "president", "politics"]


politics1 = ["republican", "wisconsin", "york", "county", "served", "senate", "president",
             "district", "ohio", "virginia", "carolina", "massachusetts", "pennsylvania",
             "democratic", "illinois", "representatives", "washington", "texas",
             "governor", "election", "elected", "law", "vermont", "missouri", "kentucky",
             "william", "judge", "tennessee", "college", "georgia"]


politics2 = ["notability", "party", "law", "government", "court", "minister", "political",
             "act", "president", "votes", "police", "council", "election", "rights", "elections",
             "committee", "democratic", "security", "union", "case", "members", "justice",
             "voters", "legal", "seats", "movement", "secretary", "federal", "stats", "ministry"]

business = ["blacklist", "business", "management", "services", "companies",
            "development", "bank", "founded", "million", "financial", "industry",
            "products", "global", "market", "marketing", "ceo", "technology",
            "investment", "inc", "social", "media", "project", "firm", "service", "energy",
            "economic", "community", "corporation", "government", "ltd"]

base = ['BUY AND HOLD',
        'DOW JONES',
        'act',
        'arts',
        'banking',
        'bonds',
        'bubble',
        'buy',
        'cancer',
        'car',
        'carolina',
        'case',
        'cash',
        'chance',
        'college',
        'color',
        'committee',
        'conflict',
        'consume',
        'consumption',
        'conty',
        'council',
        'court',
        'crash',
        'credit',
        'crisis',
        'culture',
        'debt',
        'default',
        'democratic',
        'derivatives',
        'district',
        'dividend',
        'dow jones',
        'earnings',
        'earths',
        'economics',
        'economy',
        'elected',
        'election',
        'elections',
        'energy',
        'environment',
        'fed',
        'federal',
        'finance',
        'financial',
        'fine',
        'fond',
        'food',
        'forex',
        'freedom',
        'fun',
        'gain',
        'gains',
        'garden',
        'georgia',
        'gold',
        'government',
        'governor',
        'greed',
        'growth',
        'happy',
        'headlines',
        'health',
        'hedge',
        'holiday',
        'home',
        'house',
        'housing',
        'illinois',
        'inflation',
        'invest',
        'investment',
        'judge',
        'justice',
        'kentucky',
        'kitchen',
        'labor',
        'law',
        'legal',
        'leverage',
        'lifestyle',
        'loss',
        'market',
        'markets',
        'marriage',
        'massachusetts',
        'members',
        'metals',
        'minister',
        'ministry',
        'missouri',
        'money',
        'movement',
        'movie',
        'nasdaq',
        'notability',
        'nyse',
        'office',
        'ohio',
        'oil',
        'opportunity',
        'ore',
        'party',
        'pennsylvania',
        'police',
        'political',
        'politics',
        'portfolio',
        'present',
        'president',
        'profit',
        'rare',
        'religion',
        'representatives',
        'republican',
        'restaurant',
        'return',
        'returns',
        'revenue',
        'rich',
        'rights',
        'ring',
        'risk',
        'seats',
        'secretary',
        'security',
        'sell',
        'selling',
        'senate',
        'served',
        'short',
        'society',
        'stats',
        'stock',
        'stocks',
        'success',
        'tennessee',
        'texas',
        'tourism',
        'trader',
        'train',
        'transaction',
        'travel',
        'unemployment',
        'union',
        'vermount',
        'virginia',
        'voter',
        'votes',
        'war',
        'washington',
        'water',
        'william',
        'winsconsin',
        'world',
        'york',
        'wisconsin',
        'county',
        'vermont',
        'voters',
        'blacklist',
        'business',
        'management',
        'services',
        'companies',
        'development',
        'bank',
        'founded',
        'million',
        'industry',
        'products',
        'global',
        'marketing',
        'ceo',
        'technology',
        'inc',
        'social',
        'media',
        'project',
        'firm',
        'service',
        'economic',
        'community',
        'corporation',
        'ltd']
